services:
  ldap:
    build:
      context: .
    ports:
      - "389:389"
      - "636:636"
    environment:
      - STORAGE_URI=jclouds:s3:http://minio:9000
      - STORAGE_BUCKET_NAME=dicom-bucket
      - STORAGE_BUCKET_ENDPOINT=http://minio:9000
      - STORAGE_BUCKET_PASSWORD=minioadmin
      - STORAGE_BUCKET_USERNAME=minioadmin
      - STORAGE_BUCKET_PATHSTYLE=true
      - STORAGE_BUCKET_VIRTHOST=false
